// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
	"github.com/zavu-dev/zavu-go/models/components"
)

type CreateSenderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Sender created.
	Sender *components.Sender
}

func (c CreateSenderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSenderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateSenderResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateSenderResponse) GetSender() *components.Sender {
	if c == nil {
		return nil
	}
	return c.Sender
}
