// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/models/components"
)

type DeleteSenderRequest struct {
	SenderID string `pathParam:"style=simple,explode=false,name=senderId"`
}

func (d *DeleteSenderRequest) GetSenderID() string {
	if d == nil {
		return ""
	}
	return d.SenderID
}

type DeleteSenderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteSenderResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
