// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavudev/sdk-go/models/components"
)

type DeleteTemplateRequest struct {
	TemplateID string `pathParam:"style=simple,explode=false,name=templateId"`
}

func (d *DeleteTemplateRequest) GetTemplateID() string {
	if d == nil {
		return ""
	}
	return d.TemplateID
}

type DeleteTemplateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteTemplateResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
