// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavudev/sdk-go/internal/utils"
	"github.com/zavudev/sdk-go/models/components"
)

type GetContactByPhoneRequest struct {
	// E.164 phone number.
	PhoneNumber string `pathParam:"style=simple,explode=false,name=phoneNumber"`
}

func (g *GetContactByPhoneRequest) GetPhoneNumber() string {
	if g == nil {
		return ""
	}
	return g.PhoneNumber
}

type GetContactByPhoneResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Contact details.
	Contact *components.Contact
}

func (g GetContactByPhoneResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetContactByPhoneResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetContactByPhoneResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetContactByPhoneResponse) GetContact() *components.Contact {
	if g == nil {
		return nil
	}
	return g.Contact
}
