// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavudev/sdk-go/internal/utils"
	"github.com/zavudev/sdk-go/models/components"
)

type GetContactRequest struct {
	ContactID string `pathParam:"style=simple,explode=false,name=contactId"`
}

func (g *GetContactRequest) GetContactID() string {
	if g == nil {
		return ""
	}
	return g.ContactID
}

type GetContactResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Contact details.
	Contact *components.Contact
}

func (g GetContactResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetContactResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetContactResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetContactResponse) GetContact() *components.Contact {
	if g == nil {
		return nil
	}
	return g.Contact
}
