// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavudev/sdk-go/internal/utils"
	"github.com/zavudev/sdk-go/models/components"
)

type GetMessageRequest struct {
	MessageID string `pathParam:"style=simple,explode=false,name=messageId"`
}

func (g *GetMessageRequest) GetMessageID() string {
	if g == nil {
		return ""
	}
	return g.MessageID
}

type GetMessageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Message details.
	MessageResponse *components.MessageResponse
}

func (g GetMessageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMessageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetMessageResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMessageResponse) GetMessageResponse() *components.MessageResponse {
	if g == nil {
		return nil
	}
	return g.MessageResponse
}
