// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
	"github.com/zavu-dev/zavu-go/models/components"
)

type GetSenderRequest struct {
	SenderID string `pathParam:"style=simple,explode=false,name=senderId"`
}

func (g *GetSenderRequest) GetSenderID() string {
	if g == nil {
		return ""
	}
	return g.SenderID
}

type GetSenderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Sender details.
	Sender *components.Sender
}

func (g GetSenderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSenderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetSenderResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSenderResponse) GetSender() *components.Sender {
	if g == nil {
		return nil
	}
	return g.Sender
}
