// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
	"github.com/zavu-dev/zavu-go/models/components"
)

type GetTemplateRequest struct {
	TemplateID string `pathParam:"style=simple,explode=false,name=templateId"`
}

func (g *GetTemplateRequest) GetTemplateID() string {
	if g == nil {
		return ""
	}
	return g.TemplateID
}

type GetTemplateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Template details.
	Template *components.Template
}

func (g GetTemplateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTemplateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetTemplateResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTemplateResponse) GetTemplate() *components.Template {
	if g == nil {
		return nil
	}
	return g.Template
}
