// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
	"github.com/zavu-dev/zavu-go/models/components"
)

type IntrospectPhoneResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Phone number introspection result.
	PhoneIntrospectionResponse *components.PhoneIntrospectionResponse
}

func (i IntrospectPhoneResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IntrospectPhoneResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (i *IntrospectPhoneResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IntrospectPhoneResponse) GetPhoneIntrospectionResponse() *components.PhoneIntrospectionResponse {
	if i == nil {
		return nil
	}
	return i.PhoneIntrospectionResponse
}
