// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
	"github.com/zavu-dev/zavu-go/models/components"
	"github.com/zavu-dev/zavu-go/optionalnullable"
)

type ListMessagesRequest struct {
	Status *components.MessageStatus `queryParam:"style=form,explode=true,name=status"`
	To     *string                   `queryParam:"style=form,explode=true,name=to"`
	// Delivery channel.
	Channel *components.Channel `queryParam:"style=form,explode=true,name=channel"`
	Limit   *int64              `default:"50" queryParam:"style=form,explode=true,name=limit"`
	Cursor  *string             `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListMessagesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListMessagesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListMessagesRequest) GetStatus() *components.MessageStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListMessagesRequest) GetTo() *string {
	if l == nil {
		return nil
	}
	return l.To
}

func (l *ListMessagesRequest) GetChannel() *components.Channel {
	if l == nil {
		return nil
	}
	return l.Channel
}

func (l *ListMessagesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListMessagesRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

// ListMessagesResponseBody - List of messages.
type ListMessagesResponseBody struct {
	Items      []components.Message                      `json:"items"`
	NextCursor optionalnullable.OptionalNullable[string] `json:"nextCursor,omitzero"`
}

func (l *ListMessagesResponseBody) GetItems() []components.Message {
	if l == nil {
		return []components.Message{}
	}
	return l.Items
}

func (l *ListMessagesResponseBody) GetNextCursor() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

type ListMessagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of messages.
	Object *ListMessagesResponseBody
}

func (l ListMessagesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListMessagesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (l *ListMessagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListMessagesResponse) GetObject() *ListMessagesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
