// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
	"github.com/zavu-dev/zavu-go/models/components"
)

// ListTemplatesResponseBody - List of templates.
type ListTemplatesResponseBody struct {
	Items []components.Template `json:"items"`
}

func (l *ListTemplatesResponseBody) GetItems() []components.Template {
	if l == nil {
		return []components.Template{}
	}
	return l.Items
}

type ListTemplatesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of templates.
	Object *ListTemplatesResponseBody
}

func (l ListTemplatesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTemplatesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (l *ListTemplatesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTemplatesResponse) GetObject() *ListTemplatesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
