// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
	"github.com/zavu-dev/zavu-go/models/components"
	"github.com/zavu-dev/zavu-go/optionalnullable"
)

type ListContactsRequest struct {
	PhoneNumber *string `queryParam:"style=form,explode=true,name=phoneNumber"`
	Limit       *int64  `default:"50" queryParam:"style=form,explode=true,name=limit"`
	Cursor      *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListContactsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListContactsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListContactsRequest) GetPhoneNumber() *string {
	if l == nil {
		return nil
	}
	return l.PhoneNumber
}

func (l *ListContactsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListContactsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

// ListContactsResponseBody - List of contacts.
type ListContactsResponseBody struct {
	Items      []components.Contact                      `json:"items"`
	NextCursor optionalnullable.OptionalNullable[string] `json:"nextCursor,omitzero"`
}

func (l *ListContactsResponseBody) GetItems() []components.Contact {
	if l == nil {
		return []components.Contact{}
	}
	return l.Items
}

func (l *ListContactsResponseBody) GetNextCursor() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

type ListContactsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of contacts.
	Object *ListContactsResponseBody
}

func (l ListContactsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListContactsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (l *ListContactsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListContactsResponse) GetObject() *ListContactsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
