// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavudev/sdk-go/internal/utils"
	"github.com/zavudev/sdk-go/models/components"
)

// ListSendersResponseBody - List of sender profiles.
type ListSendersResponseBody struct {
	Items []components.Sender `json:"items"`
}

func (l *ListSendersResponseBody) GetItems() []components.Sender {
	if l == nil {
		return []components.Sender{}
	}
	return l.Items
}

type ListSendersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of sender profiles.
	Object *ListSendersResponseBody
}

func (l ListSendersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSendersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (l *ListSendersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSendersResponse) GetObject() *ListSendersResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
