// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
	"github.com/zavu-dev/zavu-go/models/components"
)

type SendMessageRequest struct {
	// Optional sender profile ID. If omitted, the project's default sender will be used.
	ZavuSender *string                   `header:"style=simple,explode=false,name=Zavu-Sender"`
	Body       components.MessageRequest `request:"mediaType=application/json"`
}

func (s *SendMessageRequest) GetZavuSender() *string {
	if s == nil {
		return nil
	}
	return s.ZavuSender
}

func (s *SendMessageRequest) GetBody() components.MessageRequest {
	if s == nil {
		return components.MessageRequest{}
	}
	return s.Body
}

type SendMessageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Message accepted for delivery.
	MessageResponse *components.MessageResponse
}

func (s SendMessageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SendMessageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (s *SendMessageResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SendMessageResponse) GetMessageResponse() *components.MessageResponse {
	if s == nil {
		return nil
	}
	return s.MessageResponse
}
