// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavudev/sdk-go/internal/utils"
	"github.com/zavudev/sdk-go/models/components"
)

type SendReactionRequest struct {
	MessageID string `pathParam:"style=simple,explode=false,name=messageId"`
	// Optional sender profile ID. If omitted, the project's default sender will be used.
	ZavuSender *string                    `header:"style=simple,explode=false,name=Zavu-Sender"`
	Body       components.ReactionRequest `request:"mediaType=application/json"`
}

func (s *SendReactionRequest) GetMessageID() string {
	if s == nil {
		return ""
	}
	return s.MessageID
}

func (s *SendReactionRequest) GetZavuSender() *string {
	if s == nil {
		return nil
	}
	return s.ZavuSender
}

func (s *SendReactionRequest) GetBody() components.ReactionRequest {
	if s == nil {
		return components.ReactionRequest{}
	}
	return s.Body
}

type SendReactionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Reaction accepted for delivery.
	MessageResponse *components.MessageResponse
}

func (s SendReactionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SendReactionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (s *SendReactionResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SendReactionResponse) GetMessageResponse() *components.MessageResponse {
	if s == nil {
		return nil
	}
	return s.MessageResponse
}
