// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
	"github.com/zavu-dev/zavu-go/models/components"
)

type UpdateContactRequest struct {
	ContactID string                          `pathParam:"style=simple,explode=false,name=contactId"`
	Body      components.ContactUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateContactRequest) GetContactID() string {
	if u == nil {
		return ""
	}
	return u.ContactID
}

func (u *UpdateContactRequest) GetBody() components.ContactUpdateRequest {
	if u == nil {
		return components.ContactUpdateRequest{}
	}
	return u.Body
}

type UpdateContactResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Contact updated.
	Contact *components.Contact
}

func (u UpdateContactResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateContactResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateContactResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateContactResponse) GetContact() *components.Contact {
	if u == nil {
		return nil
	}
	return u.Contact
}
