// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
	"github.com/zavu-dev/zavu-go/models/components"
)

type UpdateSenderRequest struct {
	SenderID string                         `pathParam:"style=simple,explode=false,name=senderId"`
	Body     components.SenderUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateSenderRequest) GetSenderID() string {
	if u == nil {
		return ""
	}
	return u.SenderID
}

func (u *UpdateSenderRequest) GetBody() components.SenderUpdateRequest {
	if u == nil {
		return components.SenderUpdateRequest{}
	}
	return u.Body
}

type UpdateSenderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Sender updated.
	Sender *components.Sender
}

func (u UpdateSenderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSenderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSenderResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateSenderResponse) GetSender() *components.Sender {
	if u == nil {
		return nil
	}
	return u.Sender
}
