// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Channel - Delivery channel.
type Channel string

const (
	ChannelSms      Channel = "sms"
	ChannelWhatsapp Channel = "whatsapp"
)

func (e Channel) ToPointer() *Channel {
	return &e
}
func (e *Channel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sms":
		fallthrough
	case "whatsapp":
		*e = Channel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Channel: %v", v)
	}
}
