// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/zavudev/sdk-go/internal/utils"
	"time"
)

type Contact struct {
	ID string `json:"id"`
	// E.164 phone number.
	PhoneNumber string  `json:"phoneNumber"`
	CountryCode *string `json:"countryCode,omitzero"`
	// Whether the 24-hour WhatsApp window is currently open.
	WhatsappWindowOpen *bool `json:"whatsappWindowOpen,omitzero"`
	// When the contact last messaged via WhatsApp.
	LastWhatsappMessageAt *time.Time        `json:"lastWhatsappMessageAt,omitzero"`
	Metadata              map[string]string `json:"metadata,omitzero"`
	CreatedAt             *time.Time        `json:"createdAt,omitzero"`
	UpdatedAt             *time.Time        `json:"updatedAt,omitzero"`
}

func (c Contact) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Contact) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"id", "phoneNumber"}); err != nil {
		return err
	}
	return nil
}

func (c *Contact) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Contact) GetPhoneNumber() string {
	if c == nil {
		return ""
	}
	return c.PhoneNumber
}

func (c *Contact) GetCountryCode() *string {
	if c == nil {
		return nil
	}
	return c.CountryCode
}

func (c *Contact) GetWhatsappWindowOpen() *bool {
	if c == nil {
		return nil
	}
	return c.WhatsappWindowOpen
}

func (c *Contact) GetLastWhatsappMessageAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.LastWhatsappMessageAt
}

func (c *Contact) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *Contact) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *Contact) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}
