// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
)

type ContactUpdateRequest struct {
	Metadata map[string]string `json:"metadata,omitzero"`
}

func (c ContactUpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContactUpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContactUpdateRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}
