// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
)

type MessageContentContact struct {
	Name   *string  `json:"name,omitzero"`
	Phones []string `json:"phones,omitzero"`
}

func (m MessageContentContact) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MessageContentContact) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MessageContentContact) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MessageContentContact) GetPhones() []string {
	if m == nil {
		return nil
	}
	return m.Phones
}

type Button struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (b *Button) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *Button) GetTitle() string {
	if b == nil {
		return ""
	}
	return b.Title
}

type Row struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitzero"`
}

func (r *Row) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *Row) GetTitle() string {
	if r == nil {
		return ""
	}
	return r.Title
}

func (r *Row) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

type Section struct {
	Title string `json:"title"`
	Rows  []Row  `json:"rows"`
}

func (s *Section) GetTitle() string {
	if s == nil {
		return ""
	}
	return s.Title
}

func (s *Section) GetRows() []Row {
	if s == nil {
		return []Row{}
	}
	return s.Rows
}

// MessageContent - Content for non-text message types (WhatsApp only).
type MessageContent struct {
	// URL of the media file (for image, video, audio, document, sticker).
	MediaURL *string `json:"mediaUrl,omitzero"`
	// WhatsApp media ID if already uploaded.
	MediaID *string `json:"mediaId,omitzero"`
	// MIME type of the media.
	MimeType *string `json:"mimeType,omitzero"`
	// Filename for documents.
	Filename *string `json:"filename,omitzero"`
	// Latitude for location messages.
	Latitude *float64 `json:"latitude,omitzero"`
	// Longitude for location messages.
	Longitude *float64 `json:"longitude,omitzero"`
	// Name of the location.
	LocationName *string `json:"locationName,omitzero"`
	// Address of the location.
	LocationAddress *string `json:"locationAddress,omitzero"`
	// Contact cards for contact messages.
	Contacts []MessageContentContact `json:"contacts,omitzero"`
	// Interactive buttons (max 3).
	Buttons []Button `json:"buttons,omitzero"`
	// Button text for list messages.
	ListButton *string `json:"listButton,omitzero"`
	// Sections for list messages.
	Sections []Section `json:"sections,omitzero"`
	// Emoji for reaction messages.
	Emoji *string `json:"emoji,omitzero"`
	// Message ID to react to.
	ReactToMessageID *string `json:"reactToMessageId,omitzero"`
	// Template ID for template messages.
	TemplateID *string `json:"templateId,omitzero"`
	// Variables for template rendering. Keys are variable positions (1, 2, 3...).
	TemplateVariables map[string]string `json:"templateVariables,omitzero"`
}

func (m MessageContent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MessageContent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MessageContent) GetMediaURL() *string {
	if m == nil {
		return nil
	}
	return m.MediaURL
}

func (m *MessageContent) GetMediaID() *string {
	if m == nil {
		return nil
	}
	return m.MediaID
}

func (m *MessageContent) GetMimeType() *string {
	if m == nil {
		return nil
	}
	return m.MimeType
}

func (m *MessageContent) GetFilename() *string {
	if m == nil {
		return nil
	}
	return m.Filename
}

func (m *MessageContent) GetLatitude() *float64 {
	if m == nil {
		return nil
	}
	return m.Latitude
}

func (m *MessageContent) GetLongitude() *float64 {
	if m == nil {
		return nil
	}
	return m.Longitude
}

func (m *MessageContent) GetLocationName() *string {
	if m == nil {
		return nil
	}
	return m.LocationName
}

func (m *MessageContent) GetLocationAddress() *string {
	if m == nil {
		return nil
	}
	return m.LocationAddress
}

func (m *MessageContent) GetContacts() []MessageContentContact {
	if m == nil {
		return nil
	}
	return m.Contacts
}

func (m *MessageContent) GetButtons() []Button {
	if m == nil {
		return nil
	}
	return m.Buttons
}

func (m *MessageContent) GetListButton() *string {
	if m == nil {
		return nil
	}
	return m.ListButton
}

func (m *MessageContent) GetSections() []Section {
	if m == nil {
		return nil
	}
	return m.Sections
}

func (m *MessageContent) GetEmoji() *string {
	if m == nil {
		return nil
	}
	return m.Emoji
}

func (m *MessageContent) GetReactToMessageID() *string {
	if m == nil {
		return nil
	}
	return m.ReactToMessageID
}

func (m *MessageContent) GetTemplateID() *string {
	if m == nil {
		return nil
	}
	return m.TemplateID
}

func (m *MessageContent) GetTemplateVariables() map[string]string {
	if m == nil {
		return nil
	}
	return m.TemplateVariables
}
