// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/zavudev/sdk-go/internal/utils"
	"github.com/zavudev/sdk-go/optionalnullable"
	"time"
)

type Message struct {
	ID       string  `json:"id"`
	To       string  `json:"to"`
	From     *string `json:"from,omitzero"`
	SenderID *string `json:"senderId,omitzero"`
	// Delivery channel.
	Channel Channel `json:"channel"`
	// Type of message. Non-text types are WhatsApp only.
	MessageType MessageType   `json:"messageType"`
	Status      MessageStatus `json:"status"`
	// Text content or caption.
	Text *string `json:"text,omitzero"`
	// Content for non-text message types (WhatsApp only).
	Content *MessageContent `json:"content,omitzero"`
	// Message ID from the delivery provider.
	ProviderMessageID *string                                   `json:"providerMessageId,omitzero"`
	ErrorCode         optionalnullable.OptionalNullable[string] `json:"errorCode,omitzero"`
	ErrorMessage      optionalnullable.OptionalNullable[string] `json:"errorMessage,omitzero"`
	Metadata          map[string]string                         `json:"metadata,omitzero"`
	CreatedAt         time.Time                                 `json:"createdAt"`
	UpdatedAt         *time.Time                                `json:"updatedAt,omitzero"`
}

func (m Message) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Message) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"id", "to", "channel", "messageType", "status", "createdAt"}); err != nil {
		return err
	}
	return nil
}

func (m *Message) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *Message) GetTo() string {
	if m == nil {
		return ""
	}
	return m.To
}

func (m *Message) GetFrom() *string {
	if m == nil {
		return nil
	}
	return m.From
}

func (m *Message) GetSenderID() *string {
	if m == nil {
		return nil
	}
	return m.SenderID
}

func (m *Message) GetChannel() Channel {
	if m == nil {
		return Channel("")
	}
	return m.Channel
}

func (m *Message) GetMessageType() MessageType {
	if m == nil {
		return MessageType("")
	}
	return m.MessageType
}

func (m *Message) GetStatus() MessageStatus {
	if m == nil {
		return MessageStatus("")
	}
	return m.Status
}

func (m *Message) GetText() *string {
	if m == nil {
		return nil
	}
	return m.Text
}

func (m *Message) GetContent() *MessageContent {
	if m == nil {
		return nil
	}
	return m.Content
}

func (m *Message) GetProviderMessageID() *string {
	if m == nil {
		return nil
	}
	return m.ProviderMessageID
}

func (m *Message) GetErrorCode() optionalnullable.OptionalNullable[string] {
	if m == nil {
		return nil
	}
	return m.ErrorCode
}

func (m *Message) GetErrorMessage() optionalnullable.OptionalNullable[string] {
	if m == nil {
		return nil
	}
	return m.ErrorMessage
}

func (m *Message) GetMetadata() map[string]string {
	if m == nil {
		return nil
	}
	return m.Metadata
}

func (m *Message) GetCreatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CreatedAt
}

func (m *Message) GetUpdatedAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.UpdatedAt
}
