// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type MessageStatus string

const (
	MessageStatusQueued    MessageStatus = "queued"
	MessageStatusSending   MessageStatus = "sending"
	MessageStatusSent      MessageStatus = "sent"
	MessageStatusDelivered MessageStatus = "delivered"
	MessageStatusRead      MessageStatus = "read"
	MessageStatusFailed    MessageStatus = "failed"
)

func (e MessageStatus) ToPointer() *MessageStatus {
	return &e
}
func (e *MessageStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "queued":
		fallthrough
	case "sending":
		fallthrough
	case "sent":
		fallthrough
	case "delivered":
		fallthrough
	case "read":
		fallthrough
	case "failed":
		*e = MessageStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MessageStatus: %v", v)
	}
}
