// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MessageResponse struct {
	Message Message `json:"message"`
}

func (m *MessageResponse) GetMessage() Message {
	if m == nil {
		return Message{}
	}
	return m.Message
}
