// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
)

// MessageRequest - Request body to send a message.
type MessageRequest struct {
	// Recipient phone number in E.164 format.
	To string `json:"to"`
	// Delivery channel.
	Channel *Channel `json:"channel,omitzero"`
	// Type of message. Non-text types are WhatsApp only.
	MessageType *MessageType `json:"messageType,omitzero"`
	// Text body for text messages or caption for media messages.
	Text *string `json:"text,omitzero"`
	// Content for non-text message types (WhatsApp only).
	Content *MessageContent `json:"content,omitzero"`
	// Optional idempotency key to avoid duplicate sends.
	IdempotencyKey *string `json:"idempotencyKey,omitzero"`
	// Arbitrary metadata to associate with the message.
	Metadata map[string]string `json:"metadata,omitzero"`
}

func (m MessageRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MessageRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"to"}); err != nil {
		return err
	}
	return nil
}

func (m *MessageRequest) GetTo() string {
	if m == nil {
		return ""
	}
	return m.To
}

func (m *MessageRequest) GetChannel() *Channel {
	if m == nil {
		return nil
	}
	return m.Channel
}

func (m *MessageRequest) GetMessageType() *MessageType {
	if m == nil {
		return nil
	}
	return m.MessageType
}

func (m *MessageRequest) GetText() *string {
	if m == nil {
		return nil
	}
	return m.Text
}

func (m *MessageRequest) GetContent() *MessageContent {
	if m == nil {
		return nil
	}
	return m.Content
}

func (m *MessageRequest) GetIdempotencyKey() *string {
	if m == nil {
		return nil
	}
	return m.IdempotencyKey
}

func (m *MessageRequest) GetMetadata() map[string]string {
	if m == nil {
		return nil
	}
	return m.Metadata
}
