// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// MessageType - Type of message. Non-text types are WhatsApp only.
type MessageType string

const (
	MessageTypeText     MessageType = "text"
	MessageTypeImage    MessageType = "image"
	MessageTypeVideo    MessageType = "video"
	MessageTypeAudio    MessageType = "audio"
	MessageTypeDocument MessageType = "document"
	MessageTypeSticker  MessageType = "sticker"
	MessageTypeLocation MessageType = "location"
	MessageTypeContact  MessageType = "contact"
	MessageTypeButtons  MessageType = "buttons"
	MessageTypeList     MessageType = "list"
	MessageTypeReaction MessageType = "reaction"
	MessageTypeTemplate MessageType = "template"
)

func (e MessageType) ToPointer() *MessageType {
	return &e
}
func (e *MessageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "image":
		fallthrough
	case "video":
		fallthrough
	case "audio":
		fallthrough
	case "document":
		fallthrough
	case "sticker":
		fallthrough
	case "location":
		fallthrough
	case "contact":
		fallthrough
	case "buttons":
		fallthrough
	case "list":
		fallthrough
	case "reaction":
		fallthrough
	case "template":
		*e = MessageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MessageType: %v", v)
	}
}
