// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PhoneIntrospectionResponse struct {
	PhoneNumber string `json:"phoneNumber"`
	CountryCode string `json:"countryCode"`
	ValidNumber bool   `json:"validNumber"`
	// Whether a 24h WhatsApp window is open for this number.
	WhatsappWindowOpen *bool `json:"whatsappWindowOpen,omitzero"`
}

func (p *PhoneIntrospectionResponse) GetPhoneNumber() string {
	if p == nil {
		return ""
	}
	return p.PhoneNumber
}

func (p *PhoneIntrospectionResponse) GetCountryCode() string {
	if p == nil {
		return ""
	}
	return p.CountryCode
}

func (p *PhoneIntrospectionResponse) GetValidNumber() bool {
	if p == nil {
		return false
	}
	return p.ValidNumber
}

func (p *PhoneIntrospectionResponse) GetWhatsappWindowOpen() *bool {
	if p == nil {
		return nil
	}
	return p.WhatsappWindowOpen
}
