// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PhoneIntrospectionRequest struct {
	PhoneNumber string `json:"phoneNumber"`
}

func (p *PhoneIntrospectionRequest) GetPhoneNumber() string {
	if p == nil {
		return ""
	}
	return p.PhoneNumber
}
