// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReactionRequest struct {
	// Single emoji character to react with.
	Emoji string `json:"emoji"`
}

func (r *ReactionRequest) GetEmoji() string {
	if r == nil {
		return ""
	}
	return r.Emoji
}
