// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SenderUpdateRequest struct {
	Name         *string `json:"name,omitzero"`
	SetAsDefault *bool   `json:"setAsDefault,omitzero"`
}

func (s *SenderUpdateRequest) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SenderUpdateRequest) GetSetAsDefault() *bool {
	if s == nil {
		return nil
	}
	return s.SetAsDefault
}
