// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/zavudev/sdk-go/internal/utils"
)

type SenderCreateRequest struct {
	Name         string `json:"name"`
	PhoneNumber  string `json:"phoneNumber"`
	SetAsDefault *bool  `default:"false" json:"setAsDefault"`
}

func (s SenderCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SenderCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"name", "phoneNumber"}); err != nil {
		return err
	}
	return nil
}

func (s *SenderCreateRequest) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SenderCreateRequest) GetPhoneNumber() string {
	if s == nil {
		return ""
	}
	return s.PhoneNumber
}

func (s *SenderCreateRequest) GetSetAsDefault() *bool {
	if s == nil {
		return nil
	}
	return s.SetAsDefault
}
