// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/zavudev/sdk-go/internal/utils"
	"time"
)

type Capabilities struct {
	// Whether SMS is enabled for this sender.
	Sms *bool `json:"sms,omitzero"`
	// Whether WhatsApp is enabled for this sender.
	Whatsapp *bool `json:"whatsapp,omitzero"`
}

func (c *Capabilities) GetSms() *bool {
	if c == nil {
		return nil
	}
	return c.Sms
}

func (c *Capabilities) GetWhatsapp() *bool {
	if c == nil {
		return nil
	}
	return c.Whatsapp
}

type Sender struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// Phone number in E.164 format.
	PhoneNumber string `json:"phoneNumber"`
	// Whether this sender is the project's default.
	IsDefault    *bool         `default:"false" json:"isDefault"`
	Capabilities *Capabilities `json:"capabilities,omitzero"`
	CreatedAt    *time.Time    `json:"createdAt,omitzero"`
	UpdatedAt    *time.Time    `json:"updatedAt,omitzero"`
}

func (s Sender) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Sender) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"id", "name", "phoneNumber"}); err != nil {
		return err
	}
	return nil
}

func (s *Sender) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Sender) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Sender) GetPhoneNumber() string {
	if s == nil {
		return ""
	}
	return s.PhoneNumber
}

func (s *Sender) GetIsDefault() *bool {
	if s == nil {
		return nil
	}
	return s.IsDefault
}

func (s *Sender) GetCapabilities() *Capabilities {
	if s == nil {
		return nil
	}
	return s.Capabilities
}

func (s *Sender) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *Sender) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}
