// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/zavu-dev/zavu-go/internal/utils"
	"time"
)

type Status string

const (
	StatusPending  Status = "pending"
	StatusApproved Status = "approved"
	StatusRejected Status = "rejected"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "approved":
		fallthrough
	case "rejected":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type Template struct {
	ID string `json:"id"`
	// Template name (must match WhatsApp template name).
	Name string `json:"name"`
	// Language code.
	Language string `json:"language"`
	// Template body with variables: {{"{{"}}1}}, {{"{{"}}2}}, etc.
	Body string `json:"body"`
	// WhatsApp template category.
	Category WhatsAppCategory `json:"category"`
	Status   *Status          `default:"pending" json:"status"`
	// List of variable names for documentation.
	Variables []string   `json:"variables,omitzero"`
	CreatedAt *time.Time `json:"createdAt,omitzero"`
	UpdatedAt *time.Time `json:"updatedAt,omitzero"`
}

func (t Template) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Template) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"id", "name", "language", "body", "category"}); err != nil {
		return err
	}
	return nil
}

func (t *Template) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *Template) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *Template) GetLanguage() string {
	if t == nil {
		return ""
	}
	return t.Language
}

func (t *Template) GetBody() string {
	if t == nil {
		return ""
	}
	return t.Body
}

func (t *Template) GetCategory() WhatsAppCategory {
	if t == nil {
		return WhatsAppCategory("")
	}
	return t.Category
}

func (t *Template) GetStatus() *Status {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *Template) GetVariables() []string {
	if t == nil {
		return nil
	}
	return t.Variables
}

func (t *Template) GetCreatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.CreatedAt
}

func (t *Template) GetUpdatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.UpdatedAt
}
