// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/zavu-dev/zavu-go/internal/utils"
)

type TemplateCreateRequest struct {
	Name     string  `json:"name"`
	Language *string `default:"en" json:"language"`
	Body     string  `json:"body"`
	// WhatsApp template category.
	WhatsappCategory *WhatsAppCategory `json:"whatsappCategory,omitzero"`
	Variables        []string          `json:"variables,omitzero"`
}

func (t TemplateCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TemplateCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"name", "body"}); err != nil {
		return err
	}
	return nil
}

func (t *TemplateCreateRequest) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TemplateCreateRequest) GetLanguage() *string {
	if t == nil {
		return nil
	}
	return t.Language
}

func (t *TemplateCreateRequest) GetBody() string {
	if t == nil {
		return ""
	}
	return t.Body
}

func (t *TemplateCreateRequest) GetWhatsappCategory() *WhatsAppCategory {
	if t == nil {
		return nil
	}
	return t.WhatsappCategory
}

func (t *TemplateCreateRequest) GetVariables() []string {
	if t == nil {
		return nil
	}
	return t.Variables
}
