// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// WhatsAppCategory - WhatsApp template category.
type WhatsAppCategory string

const (
	WhatsAppCategoryUtility        WhatsAppCategory = "UTILITY"
	WhatsAppCategoryMarketing      WhatsAppCategory = "MARKETING"
	WhatsAppCategoryAuthentication WhatsAppCategory = "AUTHENTICATION"
)

func (e WhatsAppCategory) ToPointer() *WhatsAppCategory {
	return &e
}
func (e *WhatsAppCategory) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UTILITY":
		fallthrough
	case "MARKETING":
		fallthrough
	case "AUTHENTICATION":
		*e = WhatsAppCategory(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WhatsAppCategory: %v", v)
	}
}
