// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/zavudev/sdk-go/models/components"
)

type Error struct {
	Code     string                  `json:"code"`
	Message  string                  `json:"message"`
	Details  map[string]any          `json:"details,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
